export const ModuleRegistryFacetABI = [
  {
    type: 'event',
    name: 'ModuleInstalled',
    inputs: [
      { name: 'moduleId', type: 'bytes32', indexed: true },
      { name: 'name', type: 'string', indexed: false },
      { name: 'installedBy', type: 'address', indexed: true },
    ],
  },
  {
    type: 'event',
    name: 'ModuleUninstalled',
    inputs: [
      { name: 'moduleId', type: 'bytes32', indexed: true },
      { name: 'removedBy', type: 'address', indexed: true },
    ],
  },
  {
    type: 'function',
    name: 'installModule',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'moduleContract', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'uninstallModule',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'moduleId', type: 'bytes32' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'addModuleInstaller',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'installer', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'removeModuleInstaller',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'installer', type: 'address' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'isModuleInstaller',
    stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getModule',
    stateMutability: 'view',
    inputs: [{ name: 'moduleId', type: 'bytes32' }],
    outputs: [
      { name: 'name', type: 'string' },
      { name: 'version', type: 'string' },
      { name: 'installerContract', type: 'address' },
      { name: 'installedBy', type: 'address' },
      { name: 'installedAt', type: 'uint256' },
      { name: 'active', type: 'bool' },
    ],
  },
  {
    type: 'function',
    name: 'isModuleInstalled',
    stateMutability: 'view',
    inputs: [{ name: 'moduleId', type: 'bytes32' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'getInstalledModuleIds',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'bytes32[]' }],
  },
  {
    type: 'function',
    name: 'getModuleForSelector',
    stateMutability: 'view',
    inputs: [{ name: 'selector', type: 'bytes4' }],
    outputs: [{ name: '', type: 'bytes32' }],
  },
] as const;
