import {
  pgTable,
  text,
  timestamp,
  jsonb,
  integer,
  real,
  boolean,
} from "drizzle-orm/pg-core";

// ── Better Auth Tables ───────────────────────────────────────────────
// Generated by @better-auth/cli — do not hand-edit these columns.
// Anonymous plugin adds `isAnonymous` to `user`.

export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull(),
  image: text("image"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
  isAnonymous: boolean("is_anonymous"),
});

export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull(),
  updatedAt: timestamp("updated_at").notNull(),
});

export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at"),
  updatedAt: timestamp("updated_at"),
});

// ── Launchpad Setups ─────────────────────────────────────────────────
// Named setup snapshots saved from /emitter (LaunchpadSetupValues).

export const launchpadSetups = pgTable("launchpad_setups", {
  id: text("id").primaryKey(),                 // nanoid from client
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  config: jsonb("config").notNull(),           // LaunchpadSetupValues
});

// ── Emitter Runs ─────────────────────────────────────────────────────
// Results from /emitter/runs simulations.

export const emitterRuns = pgTable("emitter_runs", {
  id: text("id").primaryKey(),                 // "run-{timestamp}" from client
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  rounds: integer("rounds").notNull(),
  preset: text("preset"),                      // preset key or "from-setup"
  configUsed: jsonb("config_used"),
  summary: jsonb("summary").notNull(),         // EmitterRunSummary
  snapshots: jsonb("snapshots").notNull(),     // EmitterRoundSnapshot[]
});

// ── Governance Runs ──────────────────────────────────────────────────
// Results from /runs (governance/deliberation) simulations.

export const governanceRuns = pgTable("governance_runs", {
  id: text("id").primaryKey(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  rounds: integer("rounds").notNull(),
  configUsed: jsonb("config_used"),
  summary: jsonb("summary").notNull(),         // RunSummary
  snapshots: jsonb("snapshots").notNull(),     // RoundSnapshot[]
  deliberationCount: integer("deliberation_count").notNull().default(0),
  selfFundingRatio: real("self_funding_ratio"),
});
